### ISSUE TITLE
If I run cs2 as a subprocess with a randomly generated process name, how would you handle it?

### ISSUE THREAD

**Issue by MicroGame0** [ekknod/EC#101]
usermode see
![image](https://github.com/ekknod/EC/assets/134600386/7f2a04d1-30f7-40d6-8130-a828c2a0ab1d)

**Comment by MicroGame0** [comment]
![image](https://github.com/ekknod/EC/assets/134600386/9a5c7d94-67a0-4082-a194-7cbefeacc66e)

**Comment by ekknod** [comment]
EC used to find process by module name back in the days, code is still available in KM version of VM:
https://github.com/ekknod/vm/blob/main/km/vm.cpp#L81

You could implement something like that
