### ISSUE TITLE
ESP problems on Linux

### ISSUE THREAD

**Issue by fadsm** [ekknod/EC#104]
Everything is working as expected on GNOME, but all the other I've tested does show a black screen (xquartz).

I tested using Wayland vs x11, same results.

Please let me know if you need some testing, given that I know that you don't use Linux as your daily driver (kek).

I tested on KDE 6, i3 and bspwm. I use endevouros (arch), btw (TOP KEK).

**Comment by ekknod** [comment]
can you copy int main() function from this commit and give a try:
https://github.com/ekknod/EC/blob/50d0b94fc1aff4fdb5c323ed23d1ba25bf352f18/projects/LINUX/main.cpp
