### ISSUE TITLE
If its possible to use KmboxNet in EFI

### ISSUE THREAD

**Issue by ShirokoLEET** [ekknod/EC#114]
Is it possible to use kmbox for mousemove in EFI project instead of using vm::write
I failed on add #include <Winsock2.h> in project..Im unable to code it in kernel.cpp idk where i should code it

**Comment by monstercheat** [comment]
> Is it possible to use kmbox for mousemove in EFI project instead of using vm::write I think this bypasses some of the mouse behavior detection.but I'm failing at including <winsock2.h>(maybe im suck) I dont know how to include <winsock2.h>in cs2.cpp because include windows.h is already included in utils.cpp.If I include winsock2.h in cs2.cpp I will get the error.Anyways could i fix it?

all its possible 👍

**Comment by ShirokoLEET** [comment]
> > 是否可以在 EFI 项目中使用 kmbox 进行鼠标移动而不是使用 vm：：write 我认为这绕过了一些鼠标行为检测，但我未能包含 <winsock2.h>（也许我很糟糕）我不知道如何在 cs2.cpp 中包含 <winsock2.h>，因为 include windows.h 已经包含在 utils.cpp.If I include winsock2.h in cs2.cpp I will get the error.无论如何，我可以修复它吗？
> 
> 一切皆有可能 👍

👍

**Comment by ShirokoLEET** [comment]
🤔

**Comment by ekknod** [comment]
EFI doesn't use vm::write

**Comment by ShirokoLEET** [comment]
so can i use kmbox in kernel mode?
