### ISSUE TITLE
EFI CS2 Sad Face Boot

### ISSUE THREAD

**Issue by MrBic** [ekknod/EC#121]
Have redownloaded and rerun boot creation.

Pass both F11 checks on restart, then ASCII Sad Face blue screen before desktop.

**Comment by Klingy23** [comment]
Hi, I have latest W11 23H2 (build 22631.3810), latest BIOS, MSI B450 Tomahawk MAX. about half a year ago, it worked but now it doesn't. Waiting for fix. Blue screen is either KMODE_EXCEPTION_NOT_HANDLED or SYSTEM_THREAD_EXCEPTION_NOT_HANDLED. Tried DISM repair and sfc /scannow. Have the same issue, nothing has worked yet.

**Comment by walterconticello** [comment]
Same here

**Comment by ApacheHelicopter3** [comment]
same

**Comment by LifeGoal** [comment]
Seems to have been caused by the latest Windows Update. Try reverting it. Worked fine for me!
