### ISSUE TITLE
ESP Apex legends | esp wont load

### ISSUE THREAD

**Issue by PowerfullPower** [ekknod/EC#124]
i only have aimbot theres no esp i tried obs overlay hooking (both methods of screen capture), also gamebar what should i do?

**Comment by monstercheat** [comment]
> i only have aimbot theres no esp i tried obs overlay hooking (both methods of screen capture), also gamebar what should i do?

need update sign ..

**Comment by dekoda-uc** [comment]
Ready, it is already updated.

**Comment by monstercheat** [comment]
> Ready, it is already updated.

Yes but usless because detected 😅
but thanks you ekknod for update

**Comment by elopu** [comment]
> > Ready, it is already updated.
> 
> Yes but usless because detected 😅 but thanks you ekknod for update


Skull Cheat, we don't want you here, you filthy dog. The cheat isn't detected unless you get manually banned or your PC is marked for some other stupidity you use. You should also thank Dekoda, who updates this repository for Apex Legends.

**Comment by monstercheat** [comment]
> > > Ready, it is already updated.
> > 
> > 
> > Yes but usless because detected 😅 but thanks you ekknod for update
> 
> Skull Cheat, we don't want you here, you filthy dog. The cheat isn't detected unless you get manually banned or your PC is marked for some other stupidity you use. You should also thank Dekoda, is who updates this repository for Apex Legends.

Never Dekoda = dogass that sell ekknod P2C fuck you

**Comment by elopu** [comment]
Get out of here and don't come back, you filthy rat. My friends and I have been using this for months and haven’t been banned, And stop spreading lies about someone you don't know.
