### ISSUE TITLE
Launching ekknod

### ISSUE THREAD

**Issue by Thxu03** [ekknod/EC#129]
When you start ekknod through the bios, a small inscription appears on the black screen for a second and throws it back into the bios
Hehuananzhi qd4 x99 motherboard BIOS version 2.18.1263 2022.

**Comment by xvenom6944** [comment]
i have had the same problem for 3 days and i really don't know what the problem is.

**Comment by Blessedsolaris** [comment]
If efi doesnt work for you, try kernel mode. its a different process but i will break it down for you here:
go to projects > km > km.sln and build the solution, then go into the new x64 folder then release and open km.cer then click install certificate, local user, place all certificates in a local store > browse then trusted root certificates store. then go back to the KM folder and run start.bat as an administrator, if it starts the service and asks for you to press any key, its loaded. dont press a key unless you want to close the cheat. happy cheating!
