### ISSUE TITLE
Km

### ISSUE THREAD

**Issue by elopu** [ekknod/EC#130]
Habibi

**Comment by blitzcheat** [comment]
> Hi, I hope you are doing well. I am sending you this message because I have been using EFI for Apex, but it seems it is now detected. I tried using KM, but it appears that Apex has CR3 enabled, which prevents obtaining the process base. That is what I think might be the problem with why the KM version is not working. I would like to know if it is possible to fix this so I can continue using the aimbot for Apex with the KM version.

just dont use all method detect

**Comment by elopu** [comment]
Efi can be detected from usermode since it is internal, but km I don't think it is so easy to detect since it reads and writes physical memory
