### ISSUE TITLE
[EFI] Apex Bluescreen

### ISSUE THREAD

**Issue by Crafttino21** [ekknod/EC#132]
Run into a Bluescreen after "EC Services Startest"

OS: Windows 11 Enterprise
OS Build: 10.0.22631 Build 2261
Motherboard: MSI A320M-A-Pro

**Comment by CowNowB** [comment]
+1

**Comment by CowNowB** [comment]
I think it is as same as #123

**Comment by khalilnajjar** [comment]
https://github.com/ekknod/EC/issues/123#issuecomment-2278938650
