### ISSUE TITLE
Black screen on BSPWM(ArchLinux)

### ISSUE THREAD

**Issue by 4efirch1k** [ekknod/EC#135]
When you launch the ekknod software it works but the cs2 is Hidden behind Black screen of tux

**Comment by martnpz** [comment]
You must have a compositor like picom running with transparency

**Comment by 4efirch1k** [comment]
> У вас должен быть композитор, например picom, работающий с прозрачностью.
Can you explain in more detail? If it's not too much trouble, I'll be very grateful.

**Comment by martnpz** [comment]
Tiling window managers has not the capacity to set effects like transparency or shadows on clients, it is necessary a compositor.
The cheat uses a SDL client called tux over the game that is transparent; so you need a compositor to set the opacity.
I use picom on Arch Linux: 
`sudo pacman -Syu picom`
Put the example config (https://raw.githubusercontent.com/yshui/picom/next/picom.sample.conf) on `~/.config/picom.conf`
Then, run picom:
`picom  --experimental-backends &`

More info on: https://wiki.archlinux.org/title/Picom

**Comment by 4efirch1k** [comment]
> У менеджеров окон Tiling нет возможности устанавливать эффекты, такие как прозрачность или тени на клиентах, необходим композитор. Чит использует клиент SDL, называемый tux, поверх игры, которая прозрачна; поэтому вам нужен композитор, чтобы установить непрозрачность. Я использую picom на Arch Linux: `sudo pacman -Syu picom` Поместите пример конфигурации ( https://raw.githubusercontent.com/yshui/picom/next/picom.sample.conf ) на `~/.config/picom.conf` Затем запустите picom: `picom --experimental-backends &`
> 
> Дополнительная информация: https://wiki.archlinux.org/title/Picom

I actually dug into the config file picom And I had fading true or something else
