### ISSUE TITLE
Aimbot human curve

### ISSUE THREAD

**Issue by isjame** [ekknod/EC#14]
Aimbot smooth should be like from fast to slow，
If you use a fixed speed to aim, it's like a robot；
Here got a cursor https://github.com/Dewera/Kalon

**Comment by kaisersoju** [comment]
Recheck the aimbot smooth function (copied below) and you will see it is going from fast to slow and not linear fixed speed. It is a well known and very basic smoothing function. If the movement appears robotic to you then your should change your fov and smooth settings. Try a very high fov and play around with smooth to see what I mean.

But feel free to modify the code if you're attempting to recreate a more human realistic movement for your personal use. You can add some randomness or more complex easing functions if you're not concerned with bloat (EFI will likely limit the size of your mapping). I've done something like this with my DMA version of EC and now I'm Silver Elite ;-).

[	if (smooth >= 1.0f) {
		if (sx < x)
			sx = sx + 1.0f + (x / smooth);
		else if (sx > x)
			sx = sx - 1.0f + (x / smooth);
		else
			sx = x;

		if (sy < y)
			sy = sy + 1.0f + (y / smooth);
		else if (sy > y)
			sy = sy - 1.0f + (y / smooth);
		else
			sy = y;
		aim_ticks = (DWORD)(smooth / 100.0f);
	}
	else {
		sx = x;
		sy = y;
	}](url)
