### ISSUE TITLE
Not working after armory - possible fix?

### ISSUE THREAD

**Issue by csirketorta** [ekknod/EC#155]
I have managed to fix it up for CS2 by replacing the get_window_data return value:

`QWORD cs2::sdl::get_window_data(QWORD window)
{
	return vm::read_i64(game_handle, window + 0x24);
}`

Do i need to fix anything else? It looks and feels working, i have trigger, aimbot and esp

**Comment by arnoldvan** [comment]
This project is abandoned, ekknod told that in this discord channel. So either update it yourself guys or move on to another cheat. Fortunately, there are plenty ud external cheats out there. For example Valthrun.

**Comment by csirketorta** [comment]
Thanks for the recommendation for using Valthrun but i'm not planning to move on from this project.
Works well, easy to run and easy to understand what is happening behind the scenes.

**Comment by ahmad-sh-gsy** [comment]
Since it's open source.
Why don't you start posting it after fixing it please?

**Comment by peachberries** [comment]
This is great, I want to learn about this. What do 0x24 and 0x178 do? Is it an offset or something else?

**Comment by alexpahhatajev** [comment]
Thanks for sharing. It works only in UM for me. Does ESP work for you in EFI as well?
