### ISSUE TITLE
Windows 11 supported?

### ISSUE THREAD

**Issue by BushidoDigital** [ekknod/EC#16]
Hi, just wanted to make sure Windows 11 was supported via UM?

I tried to run it however keep getting:
[-] vt_input not found

Winver: 2262.2134

Thanks for your project and support.

**Comment by secretccx** [comment]
Nah its not but there is a software u Can use for Windows 11, add shaneyz

sön 3 sep. 2023 kl. 00:18 skrev Alex Russell ***@***.***>:

**Comment by ekknod** [comment]
Works with Windows 11
