### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Blutornato** [ekknod/EC#2]
My brother i really wanna use your project but idk how can you please put instructions

**Comment by ksoju** [comment]
Instructions found at [learncpp.com](url)

**Comment by Blutornato** [comment]
you better found instructions there your code is trash

**Comment by ksoju** [comment]
Seems you've identified and resolved the matter. I suggest you close this issue and move on.

**Comment by ekknod** [comment]
> you better found instructions there your code is trash

Hopefully you will help us in future to make this code better, glad you got it sorted 👍
