### ISSUE TITLE
Windows 11, EFI, no ESP.

### ISSUE THREAD

**Issue by cqnetgraph1** [ekknod/EC#29]
just reinstalled windows 11 (22h2, build 22621.2428), don't have any green squares at player head or something like that. Aimbot and triggerbot works perfect.

playing with EFI version of cheat

**Comment by kaisersoju** [comment]
I don't think full screen mode shows esp. Try it with windowed mode.

**Comment by GitZurah** [comment]
use game bar while you're in fullscreen and pin something of it to the screen
