### ISSUE TITLE
Support for Moonlight/Sunshine

### ISSUE THREAD

**Issue by KillaBoi** [ekknod/EC#31]
Hi!!

I'm trying to make the SDL overlay transparent so that I can support it working with programs such as Moonlight or Sunshine so that I can stream the gameplay from the second PC to the Main PC in the case of DMA without having to use a fuser or another HDMI merging device. 

I have made one alteration which has helped which was to add the following line to keep the overlay on top of Moonlight ```SDL_SetWindowAlwaysOnTop(window, SDL_TRUE)``` however whenever I do this, it still shows the window (now on top of Moonlight) albeit still with the black background of the overlay...

Is there a way to make this transparent? Do I need to switch to another library in order to achieve this? The only things I have found that I have seen with SDL is that I would need to use windows functions such as `SetWindowLongA` and `SetLayeredWindowAttributes` to try and force the overlay to change to transparent by either keying out the colour of the background or by switching to another method but none of these don't really seem to work...

Also the FPS of the overlay seems to be very slow, is this calculated somehow or can it be changed? I have tried to use the flags ```SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED``` to try and force the overlay to speed up but it still seems very choppy...

Thanks!

**Comment by Megalounge** [comment]
better check the usermode version of EC where you can see how it renders transparent window

**Comment by KillaBoi** [comment]
> better check the usermode version of EC where you can see how it renders transparent window

OOOOO i see, that is amazing ty, it doesn't create a window and interact with that per se but just interacts with the surface, gotcha, thank you so much for the info!!
