### ISSUE TITLE
EFI esp box not working(

### ISSUE THREAD

**Issue by Stalk3rx** [ekknod/EC#34]
Hello ekknod and others. How to enable ESP boxes in EFI mode? I changed the resolution to windowed and full screen in a window - to no avail. By the way: when I changed the screen resolution, green boxes appeared for a split second. System: Windows 10 22H2.

**Comment by Stalk3rx** [comment]
ESP only worked after connecting an external monitor (I have a laptop).

**Comment by haydenpog** [comment]
I've been fucking around with it recently aswell, seems like an issue related to the monitor. For me it draws but doesn't clear so you see a gazillion boxes around. Had another GDI program from csgo which seemed to work fine so I have no idea, when updating to cs2 it started to have the new issues like you said, so possibly an x64 vs x86 type beat.

**Comment by Stalk3rx** [comment]
Perhaps, need to add a monitor check to the code. Finded something: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdisplaymonitors. I tried to add it to the code, but I get all sorts of errors(

**Comment by DeadlyOmega** [comment]
For me it worked by connecting my monitor with HDMI instead of display port, maybe this could help someone else who stumbles upon this problem in the future ;)
