### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by L1berat1on** [ekknod/EC#5]
Can't I use kdmapper to load the driver? I used kdmapper to load and then triggered the blue screen

**Comment by L1berat1on** [comment]
When I use start.bat，CMDTips：
Windows could not verify the digital signature of the driver required for this device. Some software or hardware has changed recently, and the file with incorrect signature or damaged file may be installed, or the file installed may be malicious software of unknown origin.

**Comment by ksoju** [comment]
[https://learn.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option](url)

You'll need to ask the devs of kdmapper for support and troubleshooting loading of the driver.

**Comment by FoxTimo** [comment]
You cant unload manual mapped drivers. This will cause a blue screen when using kdmapper. I dont want to spoonfeed but if you read the source carefully you will figure out what you have to do.
