### ISSUE TITLE
not an issue but a challenge :>

### ISSUE THREAD

**Issue by wilczek2137** [ekknod/EC#51]
Hi. i challenge you to make your own working and being updated cheats for Dayz. just normal dayz not pirate or something. aimbot and ESP and maybe a vievmodel FOV.  i hope you accept my challenge and post that cheats into EXloader  :>

**Comment by kaisersoju** [comment]
You created a new account to say this? Just go find a p2c or code it yourself. Jeez the game is like 2018.
