### ISSUE TITLE
ESP only works when i open gamebar

### ISSUE THREAD

**Issue by larcencial** [ekknod/EC#53]
Hi, aimbot and triggerbot works perfectly but ESP only working while gamebar is open and when i close gamebar esp also closing too what should i do i have ryzen cpu nvidia gp, i tried to pin something on gamebar but didn't worked

![gamebaron](https://github.com/ekknod/EC/assets/14093933/46303f4c-ab14-4124-b431-0e08fa07e9d2)

![gamebaroff](https://github.com/ekknod/EC/assets/14093933/032e49f8-563c-46a7-9fb3-f3806a9e74b1)

**Comment by ekknod** [comment]
Windows Registry Editor Version 5.00
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm]
"OverlayTestMode"=dword:00000005

**Comment by larcencial** [comment]
thank you legend! @ekknod ♡
