### ISSUE TITLE
Standalone rcs doesn't seem to work anymore? 

### ISSUE THREAD

**Issue by Cra4ck** [ekknod/EC#6]
Standalone rcs doesn't seem to work anymore? I like to modify ±0.022F to ±0.040F to make the rcs more legit, but it seems it no longer works now, how do I fix it?

**Comment by ksoju** [comment]
I believe cl_pitch and cl_yaw are locked to 0.022f by valve servers. I tried changing them a few months ago without success. Changing the values might work on community servers however.

**Comment by Cra4ck** [comment]
> I believe cl_pitch and cl_yaw are locked to 0.022f by valve servers. I tried changing them a few months ago without success. Changing the values might work on community servers however.

Yes, I am using it on the community server. I removed the comment code and rcs works fine.
