### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by dziadasdwas** [ekknod/EC#61]
first i turned of my anti-virus. And then i clicked lunch button on exloader and the EC window opens in MD and there is this
![image](https://github.com/ekknod/EC/assets/159458529/dc3004e7-cc8c-4b88-926c-8a6034b21ea5)

**Comment by kaisersoju** [comment]
ExLoader is unaffiliated with this project so I have no comment on their use of EC. Which did you launch first? CS2 or EC? Try both ways. If both ways fail then ask ExLoader for support. Good luck.

**Comment by dziadasdwas** [comment]
first i opend the cs2
