### ISSUE TITLE
Hack doesn't work on certain guns

### ISSUE THREAD

**Issue by NoRussians** [ekknod/EC#62]
The hack does not work on Galil AR but works on AK-47 in T side. Also, the hack doesn't work on M4A1s but works on Famas in CT side. What can I do to fix this? Also sometimes it's missing some opponents. (Hacks are tested on casual)
![image](https://github.com/ekknod/EC/assets/159515990/895df4ba-b9f6-4293-9cad-5968328d267b)
![image](https://github.com/ekknod/EC/assets/159515990/deab9237-1ed6-448a-bc61-e59d69bd5c01)

**Comment by GitZurah** [comment]
+, there have always been issues with some weapons not working as outlined [here](https://github.com/ekknod/EC/issues/44) but after the recent CS2 update it's gotten much worse making it essentially unusable

**Comment by NoRussians** [comment]
Is it fixable? Do I have to do any sort of editing in the code to fix this? I just need the ESP working but ESP doesn't work for some of the weapon.

**Comment by ekknod** [comment]
Should be good now

**Comment by NoRussians** [comment]
Thanks man, appreciate it 🫡
BTW, is there any good injector you can suggest?? Or exloader is the only option??

**Comment by ekknod** [comment]
EC doesn't require any injector.
