### ISSUE TITLE
ESP doesn't work on linux

### ISSUE THREAD

**Issue by reggietorres** [ekknod/EC#63]

**Comment by reggietorres** [comment]
it also forces itself on the second monitor instead of the primary one

**Comment by insage1337** [comment]
linux moment

**Comment by kaisersoju** [comment]
It's true, linux gets no love. Might as well play the windows version. I recall that the developer tested it on ubuntu if the choice of distro has any importance.

**Comment by ekknod** [comment]
That's right. Linux cheat connector is made by using Ubuntu Linux. 
Sadly currently my linux network doesn't work with any network card, but serves on other purposes.
When someone says "Linux is good daily driver" I have to sadly disagree :/

**Comment by reggietorres** [comment]
if your doing it with ubuntu linux, maybe thats the reason your network card ain't working, ubuntu is shit sadly..

**Comment by kaisersoju** [comment]
[insert "I use Arch Linux" meme]

**Comment by reggietorres** [comment]
I use Gentoo, btw

**Comment by ekknod** [comment]
fixed
