### ISSUE TITLE
Aim and trigger not working

### ISSUE THREAD

**Issue by mn2xujiakun** [ekknod/EC#65]
I just found out that aim and trigger is not working for me rn, do I need a kmbox now to be able to use aimbot?

**Comment by kaisersoju** [comment]
[https://github.com/ekknod/EC/commit/f2148ec5f9f48cead70490d73b93fd0150b52e4b](url)

KMBOX seems intact. Haven't checked yet if kernel mouse driver is still active.

**Comment by math-muller** [comment]
only for DMA version, 

but key code changes;

```
317 = mouse1
318 = mouse2
319 = mouse3
320 = mouse4
321 = mouse5
```

**Comment by craxking** [comment]
> only for DMA version,
> 
> but key code changes;
> 
> ```
> 317 = mouse1
> 318 = mouse2
> 319 = mouse3
> 320 = mouse4
> 321 = mouse5
> ```
brother can you please provide the list of keycodes for all buttons of keyboard?

**Comment by snakeekard** [comment]
> [https://github.com/ekknod/EC/commit/f2148ec5f9f48cead70490d73b93fd0150b52e4b](url)
> 
> KMBOX seems intact. Haven't checked yet if kernel mouse driver is still active.

how ddo i disable?
