### ISSUE TITLE
Small issue / suggestion - Pistol Recoil

### ISSUE THREAD

**Issue by BuddyBoi** [ekknod/EC#67]
Firstly, IMO the point of this repo is to serve as a great place to learn, for DMA/EDK EFI projects.
Anybody intending on using the project as-is, would have likely already make these small changes or fixes.

But, for those less technically-inclined, I'll explain why your pistol recoil isn't working.
This is our current check for if or if not to add recoil to pistols:
`if ( weapon_class == cs::WEAPON_CLASS::Pistol )
{
	if ( num_shots < 2 )
	{
		goto skip_recoil;
	}
}`

This will not work.
This is because unless you're in downtown Chicago and have added a switch or autosear to your Glock, your shots fired when spamming a pistol will usually stay at "1".
In other terms, NumShots (ShotsFired) on your average pistol will never reach 2, even when spamming the pistol.

In-case anybody isn't sure, yes you need to add recoil to pistols
If you don't, then your aimbot will unnaturally snap to the head or TargetBone, fighting against your recoil.

**Solution:**
The easiest way to fix this, is to remove the ShotsFired check.
However, we obviously don't want to add recoil to weapons like the Deagle or R8.
I personally like to add a weapon_type of HeavyPistol, that includes both of these 'heavy' pistols.
This also makes life a lot easier for when you add weapon configs.

**Sad note - Pasting P2Cs:**
Sorry ekk, but I actually found this issue from my friend buying a certain pinned CS2 p2c on epvp.
I took a guess they hadn't changed a thing, and turned out to be right.

**Comment by M3351AN** [comment]
This is already known to everyone who has read the code and understood the functions
but thank you very much

**Comment by ekknod** [comment]
It's not bug. It's been like that on purpose since 2015. RCS with pistols is very inhuman.
