### ISSUE TITLE
Boot loop when trying to boot through usb. {NEW UPDATE}

### ISSUE THREAD

**Issue by luckystrike32111** [ekknod/EC#72]
Before the update it was working well. then when update came I downloaded the compiled file from the website now it won't boot through and when I press f11 and it says success but it restarts the pc instead of booting

>Tried to compile it myself, compatibility and the other one
> Using windows 11 22h2
>Downloaded from website
> Old compiled file still works

**Comment by vanishingfork** [comment]
skill issue lmao

it works on my machine

**Comment by ekknod** [comment]
@luckystrike32111 fixed bug. should now again work any OS / any system.

**Comment by luckystrike32111** [comment]
I tried it out it's still the same. I'm currently using the update from February right now since it still works for me.
