### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Sk4n3r** [ekknod/EC#76]
Hi , i have a problem with the cheat it open normalny it says on startup that EC is now started and to Press f11 to continue but when i open cs2 it doesnt work.
Thanks for help in advance.

**Comment by xinping1989** [comment]
what are you using? Kernel, user mode ,EFI? Be sure to run on windowed mode

**Comment by Sk4n3r** [comment]
But does the AIM bot work on 4:3 if I set the screen resolution to 4:3 and leave cs in windowed ?

**Comment by Sk4n3r** [comment]
I ve got another problem when i boot from usb stick it says to Press f11 to continue as normal and it restarts my pc and its the same all over again.
Thanks for your previous response it was really helpfull

**Comment by Sk4n3r** [comment]
> I ve got another problem when i boot from usb stick it says to Press f11 to continue as normal and it restarts my pc and its the same all over again. Thanks for your previous response it was really helpfull

Its in a loop and doesnt boot

**Comment by xinping1989** [comment]
same issue i reported and a couple of users as well thought it was fixed last update

**Comment by Sk4n3r** [comment]
> same issue i reported and a couple of users as well thought it was fixed last update

i downloaded the new version and it doesnt work
