### ISSUE TITLE
CSGO driver drawing high power causing processor to heat up

### ISSUE THREAD

**Issue by SwagsRGB** [ekknod/EC#9]
Whenever I boot to use the CSGO driver my CPU temps stay at 70C at idle constantly and start drawing  10-12W power on CPU at idle as measured by throttlestop, doesnt occur when booting normally. Doesnot happen with the Apex driver.
![image](https://user-images.githubusercontent.com/69312785/198016593-613dfdec-c615-44d9-b99c-b700926718c2.png)

**Comment by ekknod** [comment]
Thank you. I will figure out if everything alright :)
although 70c sounds completely safe temp,
maybe just CPU doesn't drop clocks at IDLE level when the driver is loaded.

**Comment by SwagsRGB** [comment]
So without the driver temps reach around 78 after around an hour while with it loaded my cpu gets thermal throttled so it reaches 95 atleast once, but when i checked its around 88

**Comment by ekknod** [comment]
I wonder if it can be underclocked some way (laptop). In my PC idle 40c, EC loaded 50c.

**Comment by SwagsRGB** [comment]
My PC idles at 40c as well, but something is using only a single core of my cpu @ 100% capacity once I load the driver, but cant figure out what. Its ok ig, still it is kinda strange. Like not even my whole cpu, just a single core
