### ISSUE TITLE
cs2 esp can't work

### ISSUE THREAD

**Issue by Enterld** [ekknod/EC#90]
cs2 esp can't work

**Comment by xinping1989** [comment]
> cs2 esp can't work

you sure you read how the config system works first? windowed and changing crosshair alpha

**Comment by StraGar0** [comment]
> > cs2 esp can't work
> 
> you sure you read how the config system works first? windowed and changing crosshair alpha

how to cahnge to crosshair alpha?

**Comment by Zane2b2t** [comment]
> > > cs2 esp can't work
> > 
> > 
> > you sure you read how the config system works first? windowed and changing crosshair alpha
> 
> how to cahnge to crosshair alpha?

in cs2's settings or using console

**Comment by StraGar0** [comment]
> > > > cs2 esp can't work
> > > 
> > > 
> > > you sure you read how the config system works first? windowed and changing crosshair alpha
> > 
> > 
> > how to cahnge to crosshair alpha?
> 
> in cs2's settings or using console

can you tell me what its the command?

**Comment by Zane2b2t** [comment]
> > > > > cs2 esp can't work
> > > > 
> > > > 
> > > > you sure you read how the config system works first? windowed and changing crosshair alpha
> > > 
> > > 
> > > how to cahnge to crosshair alpha?
> > 
> > 
> > in cs2's settings or using console
> 
> can you tell me what its the command? or you mean alpha crosshair its default crosshair?

i think you're too retarded. play the game legit

**Comment by khalilnajjar** [comment]
Go to windowed mode and drop the resolution to anything other than native. Should work fine

**Comment by MicroGame0** [comment]
review the code,

**Comment by dooziedev** [comment]
Make a .reg file and paste this:
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm]

"OverlayTestMode"=dword:00000005
`
If it still doesn't work then pin a gamebar element or use game capture from obs
