### ISSUE TITLE
EFI mode ESP can't work???

### ISSUE THREAD

**Issue by MicroGame0** [ekknod/EC#98]

**Comment by MicroGame0** [comment]
some config ,usemode can work,

**Comment by MicroGame0** [comment]
windows11 23h2 22631.3447

**Comment by dooziedev** [comment]
Make a .reg file and paste this:
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm]

"OverlayTestMode"=dword:00000005
`
If it still doesn't work then pin a gamebar element or use game capture from obs
